import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
process.env.HLTPC_STORAGE='local';
process.env.HLTPC_LOCAL_DATA_DIR=fs.mkdtempSync(path.resolve('artifacts/community-test-'));
process.env.HLTPC_OWNER_USERNAME='test-owner';
process.env.HLTPC_OWNER_PASSWORD='owner-password-for-tests';
process.env.HLTPC_SESSION_SECRET='isolated-community-secret-for-tests';
const {handler}=require('../netlify/functions/community');
const {createSession,cookie,validateSession}=require('../netlify/functions/auth-utils');
const {getStore}=require('../netlify/functions/storage');
const owner=cookie(createSession('test-owner',process.env.HLTPC_SESSION_SECRET)).split(';')[0];
async function call(action,values,session='',options={}) {
  const event={httpMethod:values?'POST':'GET',headers:{host:'hltpc.test',origin:options.origin||'https://hltpc.test','content-type':'application/json',cookie:session,'x-nf-client-connection-ip':options.ip||'127.0.0.1'},body:values?JSON.stringify({action,...values}):'',queryStringParameters:{action,...options.query}};
  const response=await handler(event);
  return {status:response.statusCode,data:JSON.parse(response.body),cookie:response.headers['Set-Cookie']?.split(';')[0]};
}
test('community permissions, persistence, moderation, recovery and abuse limits',async()=>{
  assert.equal((await call('topic',{title:'No login',body:'Blocked'})).status,401);
  assert.equal((await call('signup',{username:'wrong',password:'password-1234'},'',{origin:'https://attacker.test'})).status,403);
  const signup=await call('signup',{username:'TestMember',password:'a-secure-test-password'});
  assert.equal(signup.status,201);assert.ok(signup.data.recoveryCode);
  assert.equal(signup.data.user.credential,undefined);
  const stored=await getStore('hltpc-community').get('user/testmember',{type:'json'});
  assert.notEqual(stored.credential.hash,'a-secure-test-password');
  assert.equal(await validateSession(signup.cookie,{}),null,'community cookies cannot authenticate as admin');
  assert.equal((await call('moderation',null,signup.cookie)).status,403);
  assert.equal((await call('signup',{username:'TESTMEMBER',password:'a-secure-test-password'})).status,409);
  assert.equal((await call('login',{username:'TestMember',password:'wrong'})).status,401);
  const login=await call('login',{username:'testmember',password:'a-secure-test-password'});assert.equal(login.status,200);
  await getStore('hltpc-content').setJSON('current',{_revision:1,_relationsVersion:1,players:[{id:'p1',name:'Player',teams:[],teamIds:[]}],teams:[{id:'t1',name:'Team'}],tournaments:[{id:'event1',name:'Event',teams:['Team'],teamIds:['t1']}],matches:[],news:[]});
  assert.equal((await call('profile',{bio:'Anonymous'})).status,401);
  assert.equal((await call('profile',{bio:'x'.repeat(501)},login.cookie)).status,422);
  assert.equal((await call('profile',{bio:'Hello',favoriteTeam:'Unknown team'},login.cookie)).status,422);
  const edited=await call('profile',{bio:'<script>literal text</script>',favoriteTeam:'Team',username:'OtherMember',active:false,version:999,credential:{}},login.cookie);
  assert.equal(edited.status,200);assert.equal(edited.data.user.username,'TestMember');assert.equal(edited.data.user.active,true);
  const publicProfile=await call('profile',null,'',{query:{username:'testmember'}});
  assert.equal(publicProfile.status,200);assert.equal(publicProfile.data.user.favoriteTeam,'Team');assert.equal(publicProfile.data.user.bio,'<script>literal text</script>');
  assert.equal(publicProfile.data.user.credential,undefined);assert.equal(publicProfile.data.user.recovery,undefined);assert.equal(publicProfile.data.user.version,undefined);
  assert.equal((await call('session',null,login.cookie)).data.user.username,'TestMember');
  const unchanged=await getStore('hltpc-community').get('user/testmember',{type:'json'});
  assert.deepEqual(unchanged.credential,stored.credential);assert.equal(unchanged.version,1);
  const created=await call('topic',{title:'A real discussion',body:'<img src=x onerror=alert(1)>',category:'CS2'},login.cookie);
  assert.equal(created.status,201);const id=created.data.id;
  const posts=await Promise.all([1,2,3].map(i=>call('post',{kind:'forum',discussionId:id,body:`reply ${i}`},login.cookie)));
  assert.ok(posts.every(p=>p.status===201));
  let discussion=await call('discussion',null,'',{query:{kind:'forum',id}});
  assert.equal(discussion.data.total,4,'concurrent replies are not lost');
  const postId=discussion.data.posts[0].id;
  assert.equal((await call('report',{kind:'forum',discussionId:id,postId,reason:'Review this post'},login.cookie)).status,200);
  const queue=await call('moderation',null,owner);assert.equal(queue.status,200);assert.equal(queue.data.reports.length,1);
  assert.equal((await call('moderation',{operation:'post',kind:'forum',discussionId:id,postId,hidden:true},login.cookie)).status,403);
  assert.equal((await call('moderation',{operation:'post',kind:'forum',discussionId:id,postId,hidden:true},owner)).status,200);
  discussion=await call('discussion',null,'',{query:{kind:'forum',id}});assert.equal(discussion.data.total,3);
  assert.equal((await call('moderation',{operation:'topic',kind:'forum',discussionId:id,locked:true},owner)).status,200);
  assert.equal((await call('post',{kind:'forum',discussionId:id,body:'Closed'},login.cookie)).status,403);
  const recovered=await call('recover',{username:'TestMember',recoveryCode:signup.data.recoveryCode,password:'new-secure-password-123'});
  assert.equal(recovered.status,200);assert.notEqual(recovered.data.recoveryCode,signup.data.recoveryCode);
  assert.equal((await call('session',null,login.cookie)).data.user,null,'password recovery revokes old sessions');
  assert.equal((await call('moderation',{operation:'user',username:'TestMember',active:false},owner)).status,200);
  assert.equal((await call('session',null,recovered.cookie)).data.user,null,'suspension revokes community access');
  assert.equal((await call('topic',{title:'Still banned',body:'Blocked'},recovered.cookie)).status,401);
  let limited;
  for(let i=0;i<12;i++) limited=await call('login',{username:'RateLimited',password:'incorrect-password'},'',{ip:'127.0.0.2'});
  assert.equal(limited.status,429);
});
